// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[id]').default>>>>
    }
    '/api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/index').default>>>>
    }
    '/api/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/user/add-user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/add-user').default>>>>
    }
    '/api/user/find-user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/find-user').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}